language: c

sudo: false

env:
  global:
    - RACKET_DIR: '~/racket'
  matrix:
    include:
      - RACKET_VERSION: 6.12
      - RACKET_VERSION: 7.3
      - RACKET_VERSION: RELEASE
      - RACKET_VERSION: HEAD
      - RACKET_VERSION: HEADCS
    allow_failures:
      - RACKET_VERSION: 7.3 # four errors in tests due to changes in Racket

before_install:
  - git clone https://github.com/greghendershott/travis-racket.git
  - cat travis-racket/install-racket.sh | bash
  - export PATH="${RACKET_DIR}/bin:${PATH}"

install:
  - raco pkg install -i --deps search-auto --link
      $TRAVIS_BUILD_DIR/r7rs-lib
      $TRAVIS_BUILD_DIR/r7rs-test

script:
  - if [[ "$RACKET_VERSION" = 5.92 || "$RACKET_VERSION" = 5.93 || "$RACKET_VERSION" = 6.0 ]];
      then raco test -p r7rs-lib r7rs-test;
      else raco test --process -ep r7rs-lib r7rs-test;
    fi
